### perceptron AND

In [2]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([[-1],[-1],[-1],[1]],dtype=np.float32)

In [3]:
np.random.seed(0)
w = np.random.normal(0.,1,(3))
print("w >> ",w)

w >>  [1.76405235 0.40015721 0.97873798]


In [4]:
input_signal = np.hstack((xs,[[1],[1],[1],[1]])) 

In [5]:
input_signal

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [6]:
y = [sum(d) for d in w*input_signal]

In [7]:
y

[0.9787379841057392, 1.3788951924729624, 2.742790330073403, 3.1429475384406267]

### perceptron learning

In [8]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([[-1],[-1],[-1],[1]],dtype=np.float32)
np.random.seed(0)
w = np.random.normal(0.,1,(3))
print("w >> ",w)
input_signal = np.hstack((xs,[[1],[1],[1],[1]])) 

w >>  [1.76405235 0.40015721 0.97873798]


In [9]:
lr = 0.1

In [10]:
rw = w
while True:
    y = [[sum(d)] for d in rw*input_signal]
    round_y = [ [1] if i[0] > 0 else [-1] for i in y]
    flg = round_y == ts
    if all(flg):
        break
    for i,n in enumerate(flg):
        if n[0] == False:
            En = ts[i][0]*input_signal[i]
            rw = rw + lr*En 
            print(rw)

[1.76405235 0.40015721 0.87873798]
[1.76405235 0.30015721 0.77873798]
[1.66405235 0.30015721 0.67873798]
[1.66405235 0.30015721 0.57873798]
[1.66405235 0.20015721 0.47873798]
[1.56405235 0.20015721 0.37873798]
[1.56405235 0.20015721 0.27873798]
[1.56405235 0.10015721 0.17873798]
[1.46405235 0.10015721 0.07873798]
[ 1.46405235  0.10015721 -0.02126202]
[ 1.46405235e+00  1.57208367e-04 -1.21262016e-01]
[ 1.36405235e+00  1.57208367e-04 -2.21262016e-01]
[ 1.26405235e+00  1.57208367e-04 -3.21262016e-01]
[ 1.16405235e+00  1.57208367e-04 -4.21262016e-01]
[ 1.06405235e+00  1.57208367e-04 -5.21262016e-01]
[ 9.64052346e-01  1.57208367e-04 -6.21262016e-01]
[ 8.64052346e-01  1.57208367e-04 -7.21262016e-01]
[ 7.64052346e-01  1.57208367e-04 -8.21262016e-01]
[ 0.86405235  0.10015721 -0.72126202]
[ 0.76405235  0.10015721 -0.82126202]


In [11]:
for i,n in enumerate(xs):
    print("input :",n,"output : ",y[i][0])

input : [0. 0.] output :  -0.8212620158942606
input : [0. 1.] output :  -0.7211048075270374
input : [1. 0.] output :  -0.05720966992659715
input : [1. 1.] output :  0.04294753844062604


### perceptron sigmoid

In [69]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([0,0,0,1],dtype=np.float32)
np.random.seed(0)
w = np.random.normal(0.,1,(3))
print("w >> ",w)
input_signal = np.hstack((xs,[[1],[1],[1],[1]])) 
lr = 0.1

w >>  [1.76405235 0.40015721 0.97873798]


In [70]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [71]:
rw = w
for i in range(5000):
    ys = sigmoid(np.dot(input_signal,rw))
    
    En = -(ts-ys)*ys*(1-ys)

    grad = np.dot(input_signal.T,En)

    rw -= lr*grad 
    print(rw)
    

[1.75887669 0.38748351 0.94629385]
[1.75355094 0.37460079 0.91339417]
[1.74807039 0.36151723 0.88004849]
[1.74243042 0.34824275 0.84626862]
[1.73662655 0.3347891  0.81206877]
[1.73065444 0.32116999 0.77746569]
[1.72451001 0.30740117 0.74247876]
[1.71818948 0.29350048 0.70713007]
[1.71168943 0.27948787 0.67144444]
[1.70500691 0.26538544 0.63544944]
[1.69813948 0.25121736 0.59917532]
[1.69108535 0.23700979 0.56265495]
[1.68384343 0.22279081 0.52592367]
[1.67641343 0.20859016 0.48901906]
[1.66879597 0.19443913 0.45198078]
[1.66099267 0.18037024 0.41485018]
[1.6530062  0.16641695 0.37767008]
[1.64484038 0.15261339 0.34048432]
[1.63650026 0.13899395 0.30333742]
[1.62799213 0.12559297 0.26627415]
[1.61932356 0.11244436 0.22933917]
[1.61050347 0.09958121 0.19257656]
[1.60154204 0.08703551 0.15602949]
[1.59245073 0.07483778 0.11973985]
[1.5832422  0.06301678 0.0837479 ]
[1.57393025 0.05159929 0.04809199]
[1.56452972 0.04060986 0.01280834]
[ 1.55505635  0.03007064 -0.02206921]
[ 1.54552664  0.0

In [72]:
for i in range(4):
    ys = sigmoid(np.dot(input_signal[i],w))
    print("input :",xs[i],"output : ",ys)

input : [0. 0.] output :  0.0008452630740809337
input : [0. 1.] output :  0.08141827807657631
input : [1. 0.] output :  0.0814184274721598
input : [1. 1.] output :  0.9027847768204669


### perceptron bias
biasを別表記にする

In [78]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([0,0,0,1],dtype=np.float32)
np.random.seed(0)
wb = np.random.normal(0.,1,(3))
w = wb[0:-1]
b = wb[-1]
print("w:",w,"b:",b)
lr = 0.1

w: [1.76405235 0.40015721] b: 0.9787379841057392


In [79]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [80]:
rw = w
rb = b
for i in range(5000):
    ys = sigmoid(np.dot(xs,rw)+rb)
    
    En = -(ts-ys)*ys*(1-ys)

    grad = np.dot(xs.T,En)
    grad_b = np.dot(np.ones([En.shape[0]]),En)
    rw -= lr*grad
    rb -= lr*grad_b
    print(rw,rb)

[1.75887669 0.38748351] 0.9462938504723678
[1.75355094 0.37460079] 0.9133941746280327
[1.74807039 0.36151723] 0.8800484943525402
[1.74243042 0.34824275] 0.8462686185801953
[1.73662655 0.3347891 ] 0.8120687658558555
[1.73065444 0.32116999] 0.7774656860340043
[1.72451001 0.30740117] 0.7424787597999982
[1.71818948 0.29350048] 0.7071300703737066
[1.71168943 0.27948787] 0.6714444417661413
[1.70500691 0.26538544] 0.6354494382526553
[1.69813948 0.25121736] 0.5991753203448931
[1.69108535 0.23700979] 0.5626549535130319
[1.68384343 0.22279081] 0.5259236672296319
[1.67641343 0.20859016] 0.48901906354446306
[1.66879597 0.19443913] 0.4519807762884264
[1.66099267 0.18037024] 0.41485018404154755
[1.6530062  0.16641695] 0.3776700820528329
[1.64484038 0.15261339] 0.3404843202176253
[1.63650026 0.13899395] 0.3033374158465502
[1.62799213 0.12559297] 0.26627415115936426
[1.61932356 0.11244436] 0.22933916609983185
[1.61050347 0.09958121] 0.19257655713472363
[1.60154204 0.08703551] 0.15602949216859535
[1.59

In [83]:
for i in range(4):
    ys = sigmoid(np.dot(xs[i],rw)+rb)
    print("input :",xs[i],"output : ",ys)

input : [0. 0.] output :  0.0008452630740809337
input : [0. 1.] output :  0.08141827807657631
input : [1. 0.] output :  0.0814184274721598
input : [1. 1.] output :  0.9027847768204669


### perceptron OR

In [85]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([0,1,1,1],dtype=np.float32)
np.random.seed(0)
wb = np.random.normal(0.,1,(3))
w = wb[0:-1]
b = wb[-1]
print("w:",w,"b:",b)
lr = 0.1

w: [1.76405235 0.40015721] b: 0.9787379841057392


In [86]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [87]:
rw = w
rb = b
for i in range(5000):
    ys = sigmoid(np.dot(xs,rw)+rb)
    
    En = -(ts-ys)*ys*(1-ys)

    grad = np.dot(xs.T,En)
    grad_b = np.dot(np.ones([En.shape[0]]),En)
    rw -= lr*grad
    rb -= lr*grad_b
#     print(rw,rb)

In [88]:
for i in range(4):
    ys = sigmoid(np.dot(xs[i],rw)+rb)
    print("input :",xs[i],"output : ",ys)

input : [0. 0.] output :  0.08035689026769402
input : [0. 1.] output :  0.9500952318233824
input : [1. 0.] output :  0.9501742881694675
input : [1. 1.] output :  0.9997593840396385


### perceptron NOT

In [98]:
import numpy as np
xs = np.array([[0],[1]],dtype=np.float32)
ts = np.array([1,0],dtype=np.float32)
np.random.seed(0)
wb = np.random.normal(0.,1,(2))
w = [wb[0]]
b = [wb[1]]
print("w:",w,"b:",b)
lr = 0.1

w: [1.764052345967664] b: [0.4001572083672233]


In [99]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [105]:
rw = w
rb = b
for i in range(5000):
    ys = sigmoid(np.dot(xs,rw)+rb)
    
    En = -(ts-ys)*ys*(1-ys)

    grad = np.dot(xs.T,En)
    grad_b = np.dot(np.ones([En.shape[0]]),En)
    rw -= lr*grad
    rb -= lr*grad_b
    print(rw,rb)

[1.7557642] [0.40150982]
[1.7474363] [0.40281228]
[1.73906804] [0.4040644]
[1.73065883] [0.40526594]
[1.72220805] [0.4064167]
[1.7137151] [0.40751643]
[1.70517935] [0.40856493]
[1.69660017] [0.40956194]
[1.68797693] [0.41050723]
[1.67930899] [0.41140055]
[1.6705957] [0.41224167]
[1.66183642] [0.41303033]
[1.65303048] [0.41376627]
[1.64417723] [0.41444923]
[1.63527598] [0.41507896]
[1.62632606] [0.41565517]
[1.61732679] [0.41617761]
[1.60827749] [0.41664599]
[1.59917745] [0.41706004]
[1.59002599] [0.41741948]
[1.58082239] [0.41772402]
[1.57156595] [0.41797337]
[1.56225595] [0.41816726]
[1.55289168] [0.41830538]
[1.54347241] [0.41838744]
[1.53399742] [0.41841314]
[1.52446598] [0.4183822]
[1.51487735] [0.41829431]
[1.50523079] [0.41814917]
[1.49552558] [0.41794648]
[1.48576096] [0.41768595]
[1.47593619] [0.41736727]
[1.46605053] [0.41699015]
[1.45610324] [0.4165543]
[1.44609356] [0.41605942]
[1.43602076] [0.41550521]
[1.42588409] [0.4148914]
[1.41568281] [0.41421769]
[1.40541618] [0.41348

In [106]:
for i in range(2):
    ys = sigmoid(np.dot(xs[i],rw)+rb)
    print("input :",xs[i],"output : ",ys)

input : [0.] output :  [0.93761202]
input : [1.] output :  [0.05052976]


### 2dense-perceptron feedforward

In [179]:
import numpy as np
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([[0],[1],[1],[0]],dtype=np.float32)
np.random.seed(0)
wb = np.random.normal(0.,1,(9))
w1 = wb[0:4].reshape(2,2)
b1 = wb[4:6]
w2 = wb[6:8].reshape(2,1)
b2 = [wb[8]]
print("w1:",w1,"\nb1:",b1,"\nw2:",w2,"\nb2:",b2)
lr = 0.1

w1: [[1.76405235 0.40015721]
 [0.97873798 2.2408932 ]] 
b1: [ 1.86755799 -0.97727788] 
w2: [[ 0.95008842]
 [-0.15135721]] 
b2: [-0.10321885179355784]


In [180]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [181]:
rw1 = w1
rb1 = b1
rw2 = w2
rb2 = b2

for i in range(5000):
    ys1 = sigmoid(np.dot(xs,rw1)+rb1)
    ys2 = sigmoid(np.dot(ys1,rw2)+rb2)
    
    En = -(ts-ys2)*ys2*(1-ys2)
#     print(En)
#     print(ys1)
#     print(ys2)
    grad_w2 = np.dot(ys1.T,En)
    grad_b2 = np.dot(np.ones([En.shape[0]]),En)
    rw2 -= lr*grad_w2
    rb2 -= lr*grad_b2
    
    
    grad_u1 = np.dot(En,rw2.T)*ys1*(1-ys1)
    grad_w1 = np.dot(xs.T,grad_u1)
    grad_b1 = np.dot(np.ones([grad_u1.shape[0]]),grad_u1)
    rw1 -= lr*grad_w1
    rb1 -= lr*grad_b1
#     print(rw1,rb1,rw2,rb2)

In [182]:
for i in range(4):
    ys1 = sigmoid(np.dot(xs[i],rw1)+rb1)
    ys2 = sigmoid(np.dot(ys1,rw2)+rb2)
    print("input :",xs[i],"output : ",ys2)

input : [0. 0.] output :  [0.09624175]
input : [0. 1.] output :  [0.90638069]
input : [1. 0.] output :  [0.90588055]
input : [1. 1.] output :  [0.10374782]


### multi-perceptron 

In [1]:
import numpy as np
import pdb
np.random.seed(0)
xs = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
ts = np.array([[0],[1],[1],[0]],dtype=np.float32)

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-1*x))

In [27]:
class FullyConnectedLayer():
    def __init__(self, in_n, out_n, use_bias=True, activation=None):
        self.w = np.random.normal(0,1,[in_n,out_n])
        if use_bias:
            self.b = np.random.normal(0,1,[out_n])
        else:
            self.b = None
        if activation is not None:
            self.activation = activation
        else:
            self.activation = None
    
    def set_lr(self, lr=0.1):
        self.lr = lr
        
    def forward(self, feature_in):
        self.f_in = feature_in
#         pdb.set_trace()
        tmp = np.dot(feature_in,self.w)
        
        if self.b is not None:
            tmp += self.b
        if self.activation is not None:
            tmp = self.activation(tmp)
        
        self.ys = tmp
        return tmp
        
    def backward(self, w_pro, grad_pro):
#         pdb.set_trace()
        grad_u = np.dot(grad_pro,w_pro.T)
        if self.activation is sigmoid:
            grad_u *= (self.ys * (1-self.ys))
        grad_w = np.dot(self.f_in.T, grad_u)
        self.w -= self.lr*grad_w
        
        if self.b is not None:
            grad_b = np.dot(np.ones([grad_u.shape[0]]), grad_u)
            self.b -= self.lr*grad_b
        
        return grad_u
    
class Model():
    def __init__(self, *args, lr=0.1):
        self.layers = args
        for l in self.layers:
            l.set_lr(lr=lr)
    
    def forward(self,x):
        for l in self.layers:
            x = l.forward(x)
        self.ys = x
        return x
        
    def backward(self,t):
        En = -(t-self.ys)*self.ys*(1-self.ys)
        grad_pro = En
        ## referensed answer  
        w_pro = np.eye(En.shape[-1])
        ##
        for l in self.layers[::-1]:
            grad_pro = l.backward(w_pro=w_pro,grad_pro=grad_pro)
            w_pro = l.w

In [28]:
model = Model(FullyConnectedLayer(in_n=2, out_n=64,activation= sigmoid),
              FullyConnectedLayer(in_n=64, out_n=32,activation= sigmoid),
              FullyConnectedLayer(in_n=32, out_n=1,activation= sigmoid))

In [29]:
for i in range(5000):
    model.forward(xs)
    model.backward(ts)

In [30]:
for i in range(4):
    out = model.forward(xs[i])
    print("input :",xs[i],"output : ",out)

input : [0. 0.] output :  [0.09058159]
input : [0. 1.] output :  [0.90379673]
input : [1. 0.] output :  [0.8994513]
input : [1. 1.] output :  [0.10370138]
